---
Name: socialprofiles
---
Page:
  extensions:
    - Innoweb\SocialProfiles\Extensions\PageExtension
PageController:
  extensions:
    - Innoweb\SocialProfiles\Extensions\PageControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialProfiles\Extensions\ConfigExtension
Innoweb\SocialProfiles\Extension\ConfigExtension:
  multisites_enable_global_settings: false
---
Only:
  classexists: 'Symbiote\Multisites\Multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\SocialProfiles\Extensions\ConfigExtension
