---
Name: socialprofiles
---
Page:
  extensions:
    - SocialProfilesPageExtension
Page_Controller:
  extensions:
    - SocialProfilesPageControllerExtension
SiteConfig:
  extensions:
    - SocialProfilesConfigExtension
SocialProfilesConfigExtension:
  multisites_enable_global_settings: false
---
Only:
  classexists: 'Multisites'
---
Site:
  extensions:
    - SocialProfilesConfigExtension
